services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: oscardbpswd
      POSTGRES_DB: oscar_movies
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
